---
- name: Ensure that Drupal site directories are present
  file:
    state: directory
    path: '{{ item.0.root }}/sites/{{ item.1.name|default("default") }}'
  with_subelements:
    - '{{ drupal_settings }}'
    - sites

- name: Ensure that Drupal settings files are present
  template:
    src: settings.php.j2
    dest: '{{ item.0.root }}/sites/{{ item.1.name|default("default") }}/{{ item.1.filename|default("settings.php") }}'
  with_subelements:
    - '{{ drupal_settings }}'
    - sites
