---
- name: Ensure that Drupal site directories are present
  file:
    state: directory
    path: '{{ item.0.root }}/sites/{{ item.1.name|default("default") }}'
  with_subelements:
    - '{{ drupal_settings }}'
    - sites
